### ISSUE TITLE
How to access token in Muffin/OAuth2.afterIdentify?

### ISSUE THREAD

**Issue by waltervos** [UseMuffin/OAuth2#3]
Hi,

In the documentation it says "Finally, once token is received, the Muffin/OAuth2.afterIdentify event is triggered. Use this to update your local tokens for example".

I've been searching high and low, but as far as I can see the token is not available in afterIdentify's callback. The provider and the $result from Oauth2Authenticate::_touch() are passed to the callback, but as far as I can see the provider doesn't store the token as a class property and $result is just the user record as it's found in the database. The token is available in the $user set on line 139 but that isn't passed to afterIdentify.

Could you point out to me how to access token data there? Or, should we perhaps make the $user variable available in the callback (change line 149 to $args = [$this->_provider, $result, $user];)?

**Comment by jadb** [comment]
The token is returned in the [`$rawData`](https://github.com/UseMuffin/OAuth2/blob/master/src/Auth/OAuthAuthenticate.php#L139) and just needs to be mapped to the user's schema.

**Comment by waltervos** [comment]
Hi @jadb,

I may well be mistaken, since I'm a cut and paste coder, but I spent a lot of time looking at the flow in your component (which is wonderful otherwise!) and I really don't think there's any way the token is still available in [`$this->dispatchEvent('Muffin/OAuth2.afterIdentify', $args);`](https://github.com/UseMuffin/OAuth2/blob/master/src/Auth/OAuthAuthenticate.php#L150). Let me explain:

I agree that the token is returned in `$rawData`. After that comes `$user = $this-_map($rawData)`, which leaves the token available in the `$user` variable.

However, when [`$result = $this->_touch($user)`](https://github.com/UseMuffin/OAuth2/blob/master/src/Auth/OAuthAuthenticate.php#L145) gets called, we loose the (renewed) token value, since that function [returns a user record if the user already exists](https://github.com/UseMuffin/OAuth2/blob/master/src/Auth/OAuthAuthenticate.php#L188):

```
protected function _touch(array $data)
{
    if ($result = $this->_findUser($data[$this->config('fields.username')])) {
        return $result;
    }
(...)
}
```

Am I missing something here?

**Comment by jadb** [comment]
Gotcha! I will check it out :)

**Comment by jadb** [comment]
Just leaving this here as note.

The `token` is also passed to the `Muffin/OAuth2.afterIdentify` event, which is the preferred way of accessing it.

The latest change makes the data returned by `_touch()` always include the same keys, which is better. Thanks for pointing it out!
